build:
  environment:
    python:
      version: 3.7.3
  nodes:
    dependencies:
      before:
        - pip install pipenv
        - pipenv install --dev
    coverage:
      tests:
        override:
          - command: './scripts/coverage.sh'
            coverage:
              file: '.coverage'
              format: 'py-cc'